{% set name = "apispec-webframeworks" %}
{% set version = "1.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: b095df4afb3d773bdf60f0a599b808fd2ca316a8e452f8ce23b10b4cb0e717bf

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - apispec >=2.0.0
    - python >=3.6

test:
  imports:
    - apispec_webframeworks
    - apispec_webframeworks.tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/marshmallow-code/apispec-webframeworks
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Web framework plugins for apispec."
  doc_url: https://pypi.org/project/apispec-webframeworks/#description
  dev_url: https://github.com/marshmallow-code/apispec-webframeworks

extra:
  recipe-maintainers:
    - ndmaxar
    - oblute
    - rluria14
