{% set name = "apispec-webframeworks" %}
{% set version = "1.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apispec-webframeworks-{{ version }}.tar.gz
  sha256: 5689288c266a2713c2f516eacc14ea2fec9b21f193edc8f659c770342b97fd81

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - apispec >=2.0.0
    - python >={{ python_min }}

test:
  imports:
    - apispec_webframeworks
    - apispec_webframeworks.tests
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/marshmallow-code/apispec-webframeworks
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Web framework plugins for apispec."
  doc_url: https://pypi.org/project/apispec-webframeworks/#description
  dev_url: https://github.com/marshmallow-code/apispec-webframeworks

extra:
  recipe-maintainers:
    - ndmaxar
    - oblute
    - rluria14
